### ISSUE TITLE
combining models

### ISSUE THREAD

**Issue by DLZML001** [luuil/Merging-Models-for-TensorFlow-Serving#1]
Hi, 
Do you think it is possible to combine two models in such a way that the output of the first model, goes as input to the second model?

**Comment by navlok-mishra** [comment]
This is what I am also interested in. 

From the repository name and description, I also started to think that it's the solution of my problem but it's doing something else which I am not interested in.

@DLZML001 If you know the solution then please let me know.

**Comment by luuil** [comment]
@DLZML001 Yes, it's possible, you can ref. to https://stackoverflow.com/questions/59381246/how-to-sequentially-combine-2-tensorflow-models.
@navlok-mishra I'll modify the description to prevent misunderstanding 🤣
