### ISSUE TITLE
Merged Model doesn't have its own signature name and other stuff?

### ISSUE THREAD

**Issue by navlok-mishra** [luuil/Merging-Models-for-TensorFlow-Serving#3]
What I understood after playing around the scripts is that it just merges two frozen model (.pb files) into single model but the merged model is still storing the information about each member models.

Earlier, I was under the impression that we can unify and aggregate the models using this script and in the Tensorflow-serving, we can use the merged model as if it is a single model. But it is not, when we deploy it in Tensorflow-serving then we are still allowed to post the query to only one of the member model. 
Note: signature_name = serving_default is hard-coded in the Tensorflow-serving which doesn't work with merged model.

My question is that 
1. How do I get single model with a unique signature name, probably serving_default?
2. What I want to achieve is that I am having multiple frozen models (pre-trained model, each on different dataset). I want to merge them so that it behaves as if there is a single model which is trained on all the member models's dataset. How do I achieve it? 

https://stackoverflow.com/questions/59381246/how-to-sequentially-combine-2-tensorflow-models
The problem mentioned in the above is what I have been trying to achieve.

From the repo. name, I thought it is what I needed but it doesn't. Please let me know if I am missing anything?

**Comment by luuil** [comment]
You are correct.

This repo is not for combine models, but for **HOT UPDATE**, as I mentioned in [Readme][readme]

> * When deploying, you only need to place the updated version of the model(merged model) in the corresponding location **without restart** the TensorFlow Serving service.
> * Hot switching can be done easily. That is, the service will not be interrupted when updating the model.

[readme]: https://github.com/luuil/Merging-Models-for-TensorFlow-Serving/blob/master/README.md#merging-models-for-tensorflow-serving
